name: tiktok_events_sdk
description: "TikTok Events Manager for Flutter. Implement the TikTok Events Manager in your iOS and Android applications in Flutter."
version: 1.0.11
homepage: https://github.com/marcelomoresco/flutter_tiktok_events_sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.tiktok_events_sdk
        pluginClass: TiktokEventsSdkPlugin
      ios:
        pluginClass: TiktokEventsSdkPlugin
